version: '3.2'
services:
  postgresql:
    image: postgres:13
    container_name: postgres_study
    ports:
      - "5432:5432"
    volumes:
      - postgres-study:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: study
      POSTGRES_USER: quintoandar
      POSTGRES_PASSWORD: 6&65*D!5*&g#%#@5d*X&$EtW7L8g*@&6
volumes:
  postgres-study: